<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TransaksiKeluarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-05',
                'jumlah_barang_keluar' => 12,
                'stok_awal_keluar' => 325,
                'stok_akhir_keluar' => 313,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:13:43',
                'updated_at' => '2024-09-12 05:21:56',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-07',
                'jumlah_barang_keluar' => 16,
                'stok_awal_keluar' => 313,
                'stok_akhir_keluar' => 297,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:14:18',
                'updated_at' => '2024-09-12 05:22:01',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-08',
                'jumlah_barang_keluar' => 20,
                'stok_awal_keluar' => 297,
                'stok_akhir_keluar' => 277,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:14:29',
                'updated_at' => '2024-09-12 05:22:05',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-09',
                'jumlah_barang_keluar' => 15,
                'stok_awal_keluar' => 277,
                'stok_akhir_keluar' => 262,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:14:39',
                'updated_at' => '2024-09-12 05:22:09',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-15',
                'jumlah_barang_keluar' => 14,
                'stok_awal_keluar' => 262,
                'stok_akhir_keluar' => 248,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:16:29',
                'updated_at' => '2024-09-12 05:22:14',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-17',
                'jumlah_barang_keluar' => 24,
                'stok_awal_keluar' => 248,
                'stok_akhir_keluar' => 224,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:16:47',
                'updated_at' => '2024-09-12 05:22:19',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-20',
                'jumlah_barang_keluar' => 12,
                'stok_awal_keluar' => 224,
                'stok_akhir_keluar' => 212,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:17:03',
                'updated_at' => '2024-09-12 05:22:22',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-21',
                'jumlah_barang_keluar' => 19,
                'stok_awal_keluar' => 212,
                'stok_akhir_keluar' => 193,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:17:42',
                'updated_at' => '2024-09-12 05:22:27',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-23',
                'jumlah_barang_keluar' => 16,
                'stok_awal_keluar' => 193,
                'stok_akhir_keluar' => 177,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:18:36',
                'updated_at' => '2024-09-12 05:22:31',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-25',
                'jumlah_barang_keluar' => 23,
                'stok_awal_keluar' => 177,
                'stok_akhir_keluar' => 154,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:19:11',
                'updated_at' => '2024-09-12 05:22:34',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-28',
                'jumlah_barang_keluar' => 21,
                'stok_awal_keluar' => 154,
                'stok_akhir_keluar' => 133,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:19:31',
                'updated_at' => '2024-09-12 05:22:37',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-29',
                'jumlah_barang_keluar' => 27,
                'stok_awal_keluar' => 133,
                'stok_akhir_keluar' => 106,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:19:43',
                'updated_at' => '2024-09-12 05:22:39',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-30',
                'jumlah_barang_keluar' => 12,
                'stok_awal_keluar' => 106,
                'stok_akhir_keluar' => 94,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:19:55',
                'updated_at' => '2024-09-12 05:22:42',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-31',
                'jumlah_barang_keluar' => 13,
                'stok_awal_keluar' => 94,
                'stok_akhir_keluar' => 81,
                'status' => 'berhasil',
                'created_at' => '2024-09-12 05:20:15',
                'updated_at' => '2024-09-12 05:22:46',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-02',
                'jumlah_barang_keluar' => 20,
                'stok_awal_keluar' => 599,
                'stok_akhir_keluar' => 579,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:48:13',
                'updated_at' => '2024-09-16 14:52:58',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-03',
                'jumlah_barang_keluar' => 15,
                'stok_awal_keluar' => 579,
                'stok_akhir_keluar' => 564,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:48:25',
                'updated_at' => '2024-09-16 14:53:03',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-04',
                'jumlah_barang_keluar' => 17,
                'stok_awal_keluar' => 564,
                'stok_akhir_keluar' => 547,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:48:36',
                'updated_at' => '2024-09-16 14:53:07',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-05',
                'jumlah_barang_keluar' => 25,
                'stok_awal_keluar' => 547,
                'stok_akhir_keluar' => 522,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:48:47',
                'updated_at' => '2024-09-16 14:53:11',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-07',
                'jumlah_barang_keluar' => 18,
                'stok_awal_keluar' => 522,
                'stok_akhir_keluar' => 504,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:48:56',
                'updated_at' => '2024-09-16 14:53:15',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-08',
                'jumlah_barang_keluar' => 20,
                'stok_awal_keluar' => 504,
                'stok_akhir_keluar' => 484,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:49:22',
                'updated_at' => '2024-09-16 14:53:19',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-09',
                'jumlah_barang_keluar' => 15,
                'stok_awal_keluar' => 484,
                'stok_akhir_keluar' => 469,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:49:33',
                'updated_at' => '2024-09-16 14:53:26',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-12',
                'jumlah_barang_keluar' => 25,
                'stok_awal_keluar' => 469,
                'stok_akhir_keluar' => 444,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:49:43',
                'updated_at' => '2024-09-16 14:53:29',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-13',
                'jumlah_barang_keluar' => 18,
                'stok_awal_keluar' => 444,
                'stok_akhir_keluar' => 426,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:50:38',
                'updated_at' => '2024-09-16 14:53:32',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-17',
                'jumlah_barang_keluar' => 22,
                'stok_awal_keluar' => 426,
                'stok_akhir_keluar' => 404,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:50:48',
                'updated_at' => '2024-09-16 14:53:34',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-18',
                'jumlah_barang_keluar' => 18,
                'stok_awal_keluar' => 404,
                'stok_akhir_keluar' => 386,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:51:03',
                'updated_at' => '2024-09-16 14:53:37',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-19',
                'jumlah_barang_keluar' => 25,
                'stok_awal_keluar' => 386,
                'stok_akhir_keluar' => 361,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:51:16',
                'updated_at' => '2024-09-16 14:53:39',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-20',
                'jumlah_barang_keluar' => 12,
                'stok_awal_keluar' => 361,
                'stok_akhir_keluar' => 349,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:51:25',
                'updated_at' => '2024-09-16 14:53:44',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-27',
                'jumlah_barang_keluar' => 24,
                'stok_awal_keluar' => 349,
                'stok_akhir_keluar' => 325,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:51:46',
                'updated_at' => '2024-09-16 14:53:47',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-28',
                'jumlah_barang_keluar' => 12,
                'stok_awal_keluar' => 325,
                'stok_akhir_keluar' => 313,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:51:54',
                'updated_at' => '2024-09-16 14:53:49',
            ],
            [
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-29',
                'jumlah_barang_keluar' => 28,
                'stok_awal_keluar' => 313,
                'stok_akhir_keluar' => 285,
                'status' => 'berhasil',
                'created_at' => '2024-09-16 14:52:03',
                'updated_at' => '2024-09-16 14:53:51',
            ],

            // Lanjutkan dengan data lainnya yang sudah diberikan
        ];


        DB::table('transaksi_barang_keluar')->insert($data);

        // DB::table('transaksi_barang_keluar')->insert([
        //     [
        //         'id' => 1,
        //         'id_customer' => 2,
        //         'id_barang' => 1,
        //         'tanggal_keluar' => '2024-01-08',
        //         'jumlah_barang_keluar' => 41,
        //         'stok_awal_keluar' => 105,
        //         'stok_akhir_keluar' => 64,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 12:25:29',
        //         'updated_at' => '2024-08-08 12:25:29',
        //     ],
        //     [
        //         'id' => 2,
        //         'id_customer' => 1,
        //         'id_barang' => 2,
        //         'tanggal_keluar' => '2024-01-08',
        //         'jumlah_barang_keluar' => 37,
        //         'stok_awal_keluar' => 68,
        //         'stok_akhir_keluar' => 31,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 12:26:07',
        //         'updated_at' => '2024-08-08 12:26:07',
        //     ],
        //     [
        //         'id' => 3,
        //         'id_customer' => 9,
        //         'id_barang' => 13,
        //         'tanggal_keluar' => '2024-01-08',
        //         'jumlah_barang_keluar' => 1,
        //         'stok_awal_keluar' => 5,
        //         'stok_akhir_keluar' => 4,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 12:26:33',
        //         'updated_at' => '2024-08-08 12:26:33',
        //     ],
        //     [
        //         'id' => 4,
        //         'id_customer' => 7,
        //         'id_barang' => 3,
        //         'tanggal_keluar' => '2024-01-08',
        //         'jumlah_barang_keluar' => 4,
        //         'stok_awal_keluar' => 96,
        //         'stok_akhir_keluar' => 92,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 12:47:28',
        //         'updated_at' => '2024-08-08 12:47:28',
        //     ],
        //     [
        //         'id' => 5,
        //         'id_customer' => 1,
        //         'id_barang' => 1,
        //         'tanggal_keluar' => '2024-02-01',
        //         'jumlah_barang_keluar' => 10,
        //         'stok_awal_keluar' => 93,
        //         'stok_akhir_keluar' => 83,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 12:50:24',
        //         'updated_at' => '2024-08-08 12:50:24',
        //     ],
        //     [
        //         'id' => 6,
        //         'id_customer' => 10,
        //         'id_barang' => 14,
        //         'tanggal_keluar' => '2024-02-08',
        //         'jumlah_barang_keluar' => 3,
        //         'stok_awal_keluar' => 7,
        //         'stok_akhir_keluar' => 4,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 12:51:03',
        //         'updated_at' => '2024-08-08 12:51:03',
        //     ],
        //     [
        //         'id' => 7,
        //         'id_customer' => 1,
        //         'id_barang' => 1,
        //         'tanggal_keluar' => '2024-03-08',
        //         'jumlah_barang_keluar' => 30,
        //         'stok_awal_keluar' => 112,
        //         'stok_akhir_keluar' => 82,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 13:00:47',
        //         'updated_at' => '2024-08-08 13:00:47',
        //     ],
        //     [
        //         'id' => 8,
        //         'id_customer' => 4,
        //         'id_barang' => 2,
        //         'tanggal_keluar' => '2024-03-08',
        //         'jumlah_barang_keluar' => 30,
        //         'stok_awal_keluar' => 33,
        //         'stok_akhir_keluar' => 3,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 13:01:01',
        //         'updated_at' => '2024-08-08 13:01:01',
        //     ],
        //     [
        //         'id' => 9,
        //         'id_customer' => 5,
        //         'id_barang' => 3,
        //         'tanggal_keluar' => '2024-03-08',
        //         'jumlah_barang_keluar' => 1,
        //         'stok_awal_keluar' => 92,
        //         'stok_akhir_keluar' => 91,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 13:01:30',
        //         'updated_at' => '2024-08-08 13:01:30',
        //     ],
        //     [
        //         'id' => 10,
        //         'id_customer' => 1,
        //         'id_barang' => 9,
        //         'tanggal_keluar' => '2024-03-08',
        //         'jumlah_barang_keluar' => 1,
        //         'stok_awal_keluar' => 30,
        //         'stok_akhir_keluar' => 29,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 13:02:25',
        //         'updated_at' => '2024-08-08 13:02:25',
        //     ],
        //     [
        //         'id' => 11,
        //         'id_customer' => 1,
        //         'id_barang' => 11,
        //         'tanggal_keluar' => '2024-03-08',
        //         'jumlah_barang_keluar' => 5,
        //         'stok_awal_keluar' => 30,
        //         'stok_akhir_keluar' => 25,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 13:02:42',
        //         'updated_at' => '2024-08-08 13:02:42',
        //     ],
        //     [
        //         'id' => 12,
        //         'id_customer' => 1,
        //         'id_barang' => 12,
        //         'tanggal_keluar' => '2024-03-08',
        //         'jumlah_barang_keluar' => 1,
        //         'stok_awal_keluar' => 3,
        //         'stok_akhir_keluar' => 2,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 13:04:07',
        //         'updated_at' => '2024-08-08 13:04:07',
        //     ],
        //     [
        //         'id' => 13,
        //         'id_customer' => 1,
        //         'id_barang' => 13,
        //         'tanggal_keluar' => '2024-03-08',
        //         'jumlah_barang_keluar' => 2,
        //         'stok_awal_keluar' => 4,
        //         'stok_akhir_keluar' => 2,
        //         'status' => 'pending',
        //         'created_at' => '2024-08-08 13:04:20',
        //         'updated_at' => '2024-08-08 13:04:20',
        //     ],
        // ]);
    }
}