<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TransaksiKeluarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('transaksi_barang_keluar')->insert([
            [
                'id' => 1,
                'id_customer' => 2,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-01-08',
                'jumlah_barang_keluar' => 41,
                'stok_awal_keluar' => 105,
                'stok_akhir_keluar' => 64,
                'status' => 'pending',
                'created_at' => '2024-08-08 12:25:29',
                'updated_at' => '2024-08-08 12:25:29',
            ],
            [
                'id' => 2,
                'id_customer' => 1,
                'id_barang' => 2,
                'tanggal_keluar' => '2024-01-08',
                'jumlah_barang_keluar' => 37,
                'stok_awal_keluar' => 68,
                'stok_akhir_keluar' => 31,
                'status' => 'pending',
                'created_at' => '2024-08-08 12:26:07',
                'updated_at' => '2024-08-08 12:26:07',
            ],
            [
                'id' => 3,
                'id_customer' => 9,
                'id_barang' => 13,
                'tanggal_keluar' => '2024-01-08',
                'jumlah_barang_keluar' => 1,
                'stok_awal_keluar' => 5,
                'stok_akhir_keluar' => 4,
                'status' => 'pending',
                'created_at' => '2024-08-08 12:26:33',
                'updated_at' => '2024-08-08 12:26:33',
            ],
            [
                'id' => 4,
                'id_customer' => 7,
                'id_barang' => 3,
                'tanggal_keluar' => '2024-01-08',
                'jumlah_barang_keluar' => 4,
                'stok_awal_keluar' => 96,
                'stok_akhir_keluar' => 92,
                'status' => 'pending',
                'created_at' => '2024-08-08 12:47:28',
                'updated_at' => '2024-08-08 12:47:28',
            ],
            [
                'id' => 5,
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-02-01',
                'jumlah_barang_keluar' => 10,
                'stok_awal_keluar' => 93,
                'stok_akhir_keluar' => 83,
                'status' => 'pending',
                'created_at' => '2024-08-08 12:50:24',
                'updated_at' => '2024-08-08 12:50:24',
            ],
            [
                'id' => 6,
                'id_customer' => 10,
                'id_barang' => 14,
                'tanggal_keluar' => '2024-02-08',
                'jumlah_barang_keluar' => 3,
                'stok_awal_keluar' => 7,
                'stok_akhir_keluar' => 4,
                'status' => 'pending',
                'created_at' => '2024-08-08 12:51:03',
                'updated_at' => '2024-08-08 12:51:03',
            ],
            [
                'id' => 7,
                'id_customer' => 1,
                'id_barang' => 1,
                'tanggal_keluar' => '2024-03-08',
                'jumlah_barang_keluar' => 30,
                'stok_awal_keluar' => 112,
                'stok_akhir_keluar' => 82,
                'status' => 'pending',
                'created_at' => '2024-08-08 13:00:47',
                'updated_at' => '2024-08-08 13:00:47',
            ],
            [
                'id' => 8,
                'id_customer' => 4,
                'id_barang' => 2,
                'tanggal_keluar' => '2024-03-08',
                'jumlah_barang_keluar' => 30,
                'stok_awal_keluar' => 33,
                'stok_akhir_keluar' => 3,
                'status' => 'pending',
                'created_at' => '2024-08-08 13:01:01',
                'updated_at' => '2024-08-08 13:01:01',
            ],
            [
                'id' => 9,
                'id_customer' => 5,
                'id_barang' => 3,
                'tanggal_keluar' => '2024-03-08',
                'jumlah_barang_keluar' => 1,
                'stok_awal_keluar' => 92,
                'stok_akhir_keluar' => 91,
                'status' => 'pending',
                'created_at' => '2024-08-08 13:01:30',
                'updated_at' => '2024-08-08 13:01:30',
            ],
            [
                'id' => 10,
                'id_customer' => 1,
                'id_barang' => 9,
                'tanggal_keluar' => '2024-03-08',
                'jumlah_barang_keluar' => 1,
                'stok_awal_keluar' => 30,
                'stok_akhir_keluar' => 29,
                'status' => 'pending',
                'created_at' => '2024-08-08 13:02:25',
                'updated_at' => '2024-08-08 13:02:25',
            ],
            [
                'id' => 11,
                'id_customer' => 1,
                'id_barang' => 11,
                'tanggal_keluar' => '2024-03-08',
                'jumlah_barang_keluar' => 5,
                'stok_awal_keluar' => 30,
                'stok_akhir_keluar' => 25,
                'status' => 'pending',
                'created_at' => '2024-08-08 13:02:42',
                'updated_at' => '2024-08-08 13:02:42',
            ],
            [
                'id' => 12,
                'id_customer' => 1,
                'id_barang' => 12,
                'tanggal_keluar' => '2024-03-08',
                'jumlah_barang_keluar' => 1,
                'stok_awal_keluar' => 3,
                'stok_akhir_keluar' => 2,
                'status' => 'pending',
                'created_at' => '2024-08-08 13:04:07',
                'updated_at' => '2024-08-08 13:04:07',
            ],
            [
                'id' => 13,
                'id_customer' => 1,
                'id_barang' => 13,
                'tanggal_keluar' => '2024-03-08',
                'jumlah_barang_keluar' => 2,
                'stok_awal_keluar' => 4,
                'stok_akhir_keluar' => 2,
                'status' => 'pending',
                'created_at' => '2024-08-08 13:04:20',
                'updated_at' => '2024-08-08 13:04:20',
            ],
        ]);
    }
}
